### ISSUE TITLE
Bad signature

### ISSUE THREAD

**Issue by kadoban** [commercialhaskell/all-cabal-hashes#10]
Has anyone looked at this: https://github.com/commercialhaskell/stack/issues/2773 ?

It appears something is going wrong with the signing process, perhaps?

**Comment by snoyberg** [comment]
I hadn't seen that issue, thanks for the ping here. I'm traveling right
now, but can probably look at it next week.

**Comment by snoyberg** [comment]
I can confirm that this isn't working as expected. @lehins This sounds like a problem in the signature code in all-cabal-tool, what do you think?

**Comment by snoyberg** [comment]
Actually, to avoid confusion, I'm going to close this issue and move discussion back to the Stack issue, where more people are paying attention.
