### ISSUE TITLE
Not updating?

### ISSUE THREAD

**Issue by ChrisPenner** [commercialhaskell/all-cabal-hashes#13]
The Readme says it's supposed to update every 30 mins, I pushed a library this afternoon and it hasn't been recognized by stack yet, checking the commit logs on the `hackage` branch show that there hasn't been a commit in 9 hours; Has something gone wrong?

**Comment by snoyberg** [comment]
The Hackage mirror is down because upstream Hackage just changed its IP address :(

**Comment by ChrisPenner** [comment]
Yikes; any news on when things will be sorted out?

**Comment by snoyberg** [comment]
I just switched to a different hostname, it should be up in the next 20 minutes I'm hoping. You happened to catch me right after I woke up and came downstairs to fix it.

**Comment by ChrisPenner** [comment]
Haha, good timing! Thanks!

**Comment by snoyberg** [comment]
Alright, everything seems to be syncing again, closing. Thanks for the report.
