### ISSUE TITLE
wai-middleware-prometheus-0.2.0 is incomplete

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-hashes#15]
The file `wai-middleware-prometheus/0.2.0/wai-middleware-prometheus.json` does not exist.

**Comment by snoyberg** [comment]
This is the same as #11. As with the others, it's an upstream issue that should be filed upstream (namely, bumping haskell/hackage-security#183).

**Comment by peti** [comment]
Would it be possible to generate the missing files and to commit them here so that tools that depend on the information provided in this repo can function even though upstream provides imperfect information?

**Comment by snoyberg** [comment]
If you'd like to send a PR, we'd probably merge it. I'm not going to make
the changes.

**Comment by peti** [comment]
Well, in that case I think I'd rather migrate to a different way of getting the information I need, like using `01-index.tar`.

**Comment by snoyberg** [comment]
The problem has been fixed by upstream.
