### ISSUE TITLE
Do these hashes relate to extra-deps?

### ISSUE THREAD

**Issue by pbrisbin** [commercialhaskell/all-cabal-hashes#18]
Apologies if this is off-topic for this repository, but my team and I have been forever trying to find a better way to add extra-deps with `sha256` values into a `stack.yaml` than our current approach of "put in a wrong thing and let `stack` tell you". I thought this repository was the answer but it seems not, so I'm wondering if you can help clarify.

As an example, https://www.stackage.org/nightly-2022-02-07/package/freckle-app-1.0.0.4 shows,

```
freckle-app-1.0.0.4@sha256:8cb624bb3e8805d626b700127690d54d1ddc736073720ac9806a3b04dd3c3216,6244
```

While https://github.com/commercialhaskell/all-cabal-hashes/blob/hackage/freckle-app/1.0.0.4/freckle-app.json shows,

```
{
  "package-hashes": {
    "SHA256":"e05c933a5e0896930359f458c5d75fd9bfc0906c2fce03c794d8a4138f777a64"},
    ...
  },
  ...,
  "package-size":30140
}
```

Are these just completely different artifacts for completely different uses, or is there any relation between the two that I can leverage to be able to just compute a sha256 of a Hackage extra-dep when needed?

**Comment by snoyberg** [comment]
The two hashes are derived in completely different ways. For stack.yaml, I'd probably advise against including the hashes these days overall, since the lock file will automatically add them for you. If you need to pin to a specific revision for some reason, either the @rev:XXX syntax would work, or at that point you could use the hashes.

**Comment by pbrisbin** [comment]
> I'd probably advise against including the hashes these days overall, since the lock file will automatically add them for you. If you need to pin to a specific revision for some reason, ... the `@rev:XXX` syntax would work

Interesting, good to know. Would be great if the suggestions coming out of `stack` and the "This version can be pinned in stack with" bit on stackage.org used this syntax too, if it's preferred now.

Thanks for the info.
