### ISSUE TITLE
Updates have stopped 4 days ago

### ISSUE THREAD

**Issue by DavHau** [commercialhaskell/all-cabal-hashes#19]
I had some [failing CI job](https://github.com/DavHau/all-cabal-json/actions/runs/3254423875/jobs/5342659723) and noticed the trigger was that `all-cabal-hashes` has not been updated since 4 days.

BTW, if I would like to host a mirror of all-cabal-hashes or all-cabal-files, where can I find the software that updates the data?

**Comment by snoyberg** [comment]
Thanks for reporting, there was an out-of-memory issue, we've just resolved it. If you'd like to run your own copy, the tool in question is [all-cabal-tool](https://github.com/commercialhaskell/all-cabal-tool).
