### ISSUE TITLE
Spock 0.7.10.0 hasn't been sync'd.

### ISSUE THREAD

**Issue by seanparsons** [commercialhaskell/all-cabal-hashes#2]
Hackage had the above version added 2 weeks ago: https://hackage.haskell.org/package/Spock-0.7.10.0
But this version doesn't exist in this repo: https://github.com/commercialhaskell/all-cabal-hashes/tree/hackage/Spock

**Comment by snoyberg** [comment]
You mean https://github.com/commercialhaskell/all-cabal-hashes/tree/hackage/Spock/0.7.10.0 ?

**Comment by seanparsons** [comment]
@snoyberg I think I may have had a brain fart in this hot weather, just now gotta find out why Stack is giving me hassles with that version.
