### ISSUE TITLE
Update job seems to have stopped three weeks ago

### ISSUE THREAD

**Issue by sternenseemann** [commercialhaskell/all-cabal-hashes#20]
Another case of https://github.com/commercialhaskell/all-cabal-hashes/issues/19, maybe?

**Comment by chreekat** [comment]
I'll look into it, it's probably related to the migration to Haskell Foundation-maintained services!

**Comment by chreekat** [comment]
Looks like there's a new package in the snapshot that uses cabal-version: 3.6, and all-cabal-tool doesn't support that version yet. I assume this has happened with other packages already, so I just need to find out what the usual solution is.

**Comment by chreekat** [comment]
Looks like the usual solution is to bump the resolver in all-cabal-tool's stack.yaml to pull in a new Cabal library. I'll get that going now.

**Comment by chreekat** [comment]
I won't finish this today. I need to update all-cabal-tool to use a newer Cabal library, which requires the bump-your-deps-and-fix-all-the-things game. Back at it tomorrow. :)

**Comment by chreekat** [comment]
Now updating again successfully. :)
