### ISSUE TITLE
Please include an SHA256 hash of the Cabal file itself

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-hashes#4]
When building these packages in Nix, we need to download the modified Cabal file in case the package has underdone revisions after the upload. This means that we need to know a checksum of the Cabal file in addition to the one we already have for the release tarball. It would be great if that hash would be included in this repository.

**Comment by snoyberg** [comment]
That's going to significantly increase the download size, which will affect
end users using this repo. I also don't think it adds any security to have
the checksum in the same location as the original file: anyone who can
compromise the latter can compromise the former too.

**Comment by peti** [comment]
The change is not intended to improve security. It's just intended to make use of the JSON files more convenient.

**Comment by snoyberg** [comment]
I'm not understanding the value this would add, since the checksum will be sitting right next to the .cabal file itself, and therefore calling `sha256sum` on that file would have the same effect.

**Comment by peti** [comment]
It's just a matter of convenience. I parse the `foo.json` file to get all meta information about the Cabal file that I need, i.e. it contains various hashes of the package tarball. The only thing it doesn't contain is the hash of the Cabal file itself. I _know_ it's trivially computable given the Cabal file, but in my code it would be easier if I wouldn't have to bother computing it.

**Comment by snoyberg** [comment]
I'm not seeing this as compelling enough, sorry. Users would end up having do download two new blobs for every revised cabal file instead of one. We have the very nice property right now that the .json files are immutable for each package/version combo, and I don't want to lose that.
