### ISSUE TITLE
The all-cabal-hashes don't seem to update.

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/all-cabal-hashes#6]
Is it any way to inspect when the index was last updated and what is the index using `stack`?

**Comment by snoyberg** [comment]
You can see when this repo last updated by checking the `hackage` branch's last commit (web version: https://github.com/commercialhaskell/all-cabal-hashes/tree/hackage).

For Stack, you can run `git log current-hackage` from `~/.stack/indices/Hackage/git-update/all-cabal-hashes`

**Comment by phadej** [comment]
After I run `stack update` the `git log` says:

```
commit db1eadfe0fe55c598613ef8ac836622c66073a24
Author: Commercial Haskell all-cabal-hashes Travis job <michael+all-cabal-hashes@snoyman.com>
Date:   Tue May 31 08:43:24 2016 +0000

    Update from Hackage at 2016-05-31T08:43:24+0000
```

which is pretty old already...

**Comment by snoyberg** [comment]
That's just 3 hours ago. Have there been Hackage uploads in the past 3 hours to trigger a new commit?

**Comment by snoyberg** [comment]
Answering my own question from: http://hackage.haskell.org/packages/recent

```
Tue May 31 11:24:58 UTC 2016    SimonMarechal     language-puppet-1.2
Tue May 31 09:47:42 UTC 2016    ChrisDone     intero-0.1.12
```

So we should be OK :)

**Comment by phadej** [comment]
Ok, seemed that 30 minute update period mentioned in the README is approximate? Cause the `swagger2-2.1` wasn't yet visible back then. Now the latest is `Update from Hackage at 2016-05-31T11:58:02+0000`, so I guess this is resolved.

Thanks!

**Comment by snoyberg** [comment]
The 30 minutes is how often we trigger a Travis build to download updates
from Hackage
