### ISSUE TITLE
The Travis job isn't starting

### ISSUE THREAD

**Issue by dtaskoff** [commercialhaskell/all-cabal-hashes#8]
There are new packages (and package updates) on hackage, which are already on [all-cabal-files](https://github.com/commercialhaskell/all-cabal-files) and not here, because the [Travis job ](https://travis-ci.org/commercialhaskell/all-cabal-hashes) hasn't been triggered in the past 22 hours.
See [#2342](https://github.com/commercialhaskell/stack/issues/2342) on stack.

**Comment by snoyberg** [comment]
It's the same as https://github.com/commercialhaskell/all-cabal-files/issues/10, let's keep the discussion there. Updates will be haphazard as I try to fix it.
